---
inputdir: /Users/mahtin/Dropbox/Icke/Work/10x/data/SARS_Teff/SARS_samples3to10   # source of bam files
workdir: /Users/mahtin/Dropbox/Icke/Work/10x/data/SARS_Teff/output/PipeOutput # here your results are created
samples: # here go all your samples
    samplesheet: sheets/SARS_sheet.csv
    genome_build: hg19   # if genome build is set, pipeline looks for 10x data in respective subfolder
metair_file: 
    /Users/mahtin/Dropbox/Icke/Work/10x/data/SARS_Teff/info/Samples-Grid All Sample Entry.csv
configs: 
    qc: configs/config_qc.yaml  ### here could be a list of dedicated yaml files for each topic
envs:
    "envMac"