---
paths: 
    base_path: /Users/martinszyska/Dropbox/Icke/Work/10x/10xBioinfo/cellrangerpipe  # abs or relative to HOME
    output_path: /Users/martinszyska/Dropbox/Icke/Work/10x/10xBioinfo/cellrangerpipe/output/snaketest
    Seqexcel: /Users/martinszyska/Dropbox/Icke/Work/Sequencing/OverviewSamplesSequencing.xlsx # abs or relative to HOME
    ADT_file: /Users/martinszyska/Dropbox/Icke/Work/Sequencing/scRNA-seq/ADT.xlsx
configs:
    CR_config: configs/cellranger_config.yml