---
paths:
    static: /fast/groups/ag_schmueck/work/ref/hg38
    output_path: /data/gpfs-1/users/szyskam_c/scratch/projects/LenaTCR1
    # all paths below are relative to snakemake root folder
    ADT_file: info/ADT.xlsx
    sample_sheet: sheets/lena_samples.csv
configs:
    CR_config: configs/cellranger_config.yml
