---
paths:
    static: /fast/groups/ag_schmueck/work/ref/hg38
    output_path: /data/gpfs-1/users/szyskam_c/scratch/projects/DRFZ10x
    # all paths below are relative to snakemake root folder
    Seqexcel: info/OverviewSamplesSequencing.xlsx
    ADT_file: info/ADT.xlsx
    sample_sheet: # sheets/test_samples.csv # sample sheet as prescendence over Seqexcel file and will be used if it is given
configs:
    CR_config: configs/cellranger_config.yml
